name: LankaLawBot CI/CD Pipeline

# This makes the robot run on Pull Requests AND when code is merged (pushed) to main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # TEST THE FRONTEND
  check-frontend:
    name: Build Next.js
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Test Build
        run: npm run build

  # TEST THE BACKEND
  check-backend:
    name: Install Python Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Requirements
        run: pip install -r requirements.txt